### ISSUE TITLE
Build failure with go1.17

### ISSUE THREAD

**Issue by navytux** [signal18/replication-manager#385]
Hello up there. When trying to build replication-manager with Go1.17.3 we are hitting the following build failure:

```console
.../replication-manager$ ./build.sh 
# github.com/signal18/replication-manager
github.com/jacobsa/fuse/internal/buffer.memclr: relocation target runtime.memclrNoHeapPointers not defined for ABI0 (but is defined for ABIInternal)
```

The problem is present on both 2.1 branch (`v2.2.6-6-ge0fd678d` revision as of today), and on develop branch (`v2.2.11-14-gc348028b` revision as of today).

Go version:

```console
.../replication-manager$ go version
go version go1.17.3 linux/amd64
```

Please see https://lab.nexedi.com/nexedi/slapos/merge_requests/1085 for more details and context.

Thanks beforehand,
Kirill

/cc @perrinjerome

**Comment by navytux** [comment]
Some analysis by @perrinjerome from https://lab.nexedi.com/nexedi/slapos/merge_requests/1085#note_145666:

---- 8< ----

replication-manager uses github.com/kahing/fusego instead of github.com/jacobsa/fuse

https://github.com/signal18/replication-manager/blob/9167a82c81af8f7be41cf51bc9be8a37dc3d8c03/go.mod#L5

kahing's fusego is old and uses assembly:

https://github.com/kahing/fusego/tree/cb66eea2377f/internal/buffer

jacobsa's one has switched to using a technique working with golang 1.17: https://github.com/jacobsa/fuse/commit/0630024b2bfb0724598a8dbccc5aa568b4379311

It seems to me the fix is to change back to jacobsa's fuse. I tried to do this ( https://github.com/signal18/replication-manager/commit/274e3dcfe5c133bd34000c3ea356b69204e2e730 ) but then run into the next problem:

```
goofys/internal/dir.go:789:24: undefined: fuseops.OpMetadata
goofys/internal/file.go:70:45: undefined: fuseops.OpMetadata
goofys/internal/goofys.go:841:27: op.Metadata undefined (type *fuseops.OpenFileOp has no field or method Metadata)
goofys/internal/goofys.go:895:26: op.Metadata undefined (type *fuseops.FlushFileOp has no field or method Metadata)
goofys/internal/goofys.go:955:40: op.Metadata undefined (type *fuseops.CreateFileOp has no field or method Metadata)
goofys/internal/handles.go:474:39: undefined: fuseops.OpMetadata
```

There's a goofys in mod.sum, but it also seems to be "vendored" in goofys folder in https://github.com/signal18/replication-manager/tree/9167a82c81af8f7be41cf51bc9be8a37dc3d8c03/goofys I tried very quickly to update there, but did not succeed.

**Comment by tanji** [comment]
This is indeed odd. We'll try to work around that.

**Comment by navytux** [comment]
Thanks, @tanji.

**Comment by perrinjerome** [comment]
Thanks a lot @svaroqui and @terwey ! we'll try this with go 1.17 and let you know if we find any issue

**Comment by navytux** [comment]
Thanks as well. I confirm that in regular Debian environment both 2.1 and develop branches started to build ok.
